### ISSUE TITLE
java.io.FileNotFoundException: Template /admin/configHubServerEdit.ftl not found

### ISSUE THREAD

**Issue by bgeveritt** [blackducksoftware/hub-bamboo#1]
I've installed the plugin, but when I click on the "Black Duck Hub Admin" link, I receive an error. It appears the "configHubServerEdit.ftl" does not get copied over during the add-on installation. Also, the case sensitivity ("Config" vs. "config") has an impact.

Version: 5.10.3
Build: 51020
Build Date: 14 Mar 2016

Request URL: http://172.16.44.100:8085/admin/configHubServer.action
Scheme: http
Server: 172.16.44.100
Port: 8085
URI: /admin/configHubServer.action
Context path:
Servlet path: /admin/configHubServer.action
Path info:
Query string:

`java.io.FileNotFoundException: Template /admin/configHubServerEdit.ftl not found.
	at freemarker.template.Configuration.getTemplate(Configuration.java:489)
	at freemarker.template.Configuration.getTemplate(Configuration.java:459)
	at org.apache.struts2.views.freemarker.FreemarkerResult.doExecute(FreemarkerResult.java:173)
	at org.apache.struts2.dispatcher.StrutsResultSupport.execute(StrutsResultSupport.java:186)
	at com.opensymphony.xwork2.DefaultActionInvocation.executeResult(DefaultActionInvocation.java:371)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:275)
	at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:265)
	at com.atlassian.bamboo.ww2.interceptors.BambooValidationInterceptor.validate(BambooValidationInterceptor.java:50)
	at com.atlassian.bamboo.ww2.interceptors.BambooValidationInterceptor.access$000(BambooValidationInterceptor.java:12)
	at com.atlassian.bamboo.ww2.interceptors.BambooValidationInterceptor$1.call(BambooValidationInterceptor.java:29)
	at com.atlassian.bamboo.ww2.interceptors.BambooValidationInterceptor$1.call(BambooValidationInterceptor.java:25)
	at com.atlassian.bamboo.util.BambooProfilingUtils.withUtilTimerStack(BambooProfilingUtils.java:39)`

**Comment by akamen** [comment]
We are on it.

**Comment by psantos1113** [comment]
Found an issue with the way we use the Bamboo persistence management of the global config.  Working on testing the issue further.

**Comment by psantos1113** [comment]
Commit 4263f1b addressed the issue uploading the plugin.
