### ISSUE TITLE
NullPointerException during plan run

### ISSUE THREAD

**Issue by bgeveritt** [blackducksoftware/hub-bamboo#2]
System Error Details
Build DUCK HUB - HUB - Default Job 12 : Error occurred while running Task 'Black Duck Hub Scan(3)' of type com.blackducksoftware.integration.hub-bamboo:hubScanTask. 
(java.lang.NullPointerException : )

Occurred: 18 Apr 2016, 11:05:49 AM 
Agent: Default Agent

`java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.blackducksoftware.integration.hub.bamboo.tasks.HubScanTask.installCLI(HubScanTask.java:227)
	at com.blackducksoftware.integration.hub.bamboo.tasks.HubScanTask.execute(HubScanTask.java:111)
	at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$124(TaskExecutorImpl.java:269)
	at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:202)
	at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:269)
	at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:108)
	at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:74)
	at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:215)
	at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:139)
	at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:130)
	at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:215)
	at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:129)
	at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:137)
	at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
	at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by psantos1113** [comment]
Traced the issue to the Atlassian SDK call used.  Need to investigate why the API call is not returning the proper value or determine if another API call needs to be made.

**Comment by psantos1113** [comment]
Commit 4263f1b addressed the issue installing the CLI in the bamboo home directory.
